// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9mvlxZ1gXJ0IGMmVqSWG1zLnkbiiDMlw',
    appId: '1:165461244282:web:2b6de2f5801e842af5fec3',
    messagingSenderId: '165461244282',
    projectId: 'wageme-29f75',
    authDomain: 'wageme-29f75.firebaseapp.com',
    databaseURL: 'https://wageme-29f75-default-rtdb.firebaseio.com',
    storageBucket: 'wageme-29f75.appspot.com',
    measurementId: 'G-LGZP9WMLVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGBQ1Fb_90dbQ8bRTT8k4I2FZQZ17TLxI',
    appId: '1:165461244282:android:2a19cf48cb247bddf5fec3',
    messagingSenderId: '165461244282',
    projectId: 'wageme-29f75',
    databaseURL: 'https://wageme-29f75-default-rtdb.firebaseio.com',
    storageBucket: 'wageme-29f75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW87OoRkm70OzEj9_ZXe-dEPVlMIiDffc',
    appId: '1:165461244282:ios:7fe573cba875ec5ef5fec3',
    messagingSenderId: '165461244282',
    projectId: 'wageme-29f75',
    databaseURL: 'https://wageme-29f75-default-rtdb.firebaseio.com',
    storageBucket: 'wageme-29f75.appspot.com',
    androidClientId: '165461244282-q6n840gepgqm58bcvvvflfnopd9gkoeg.apps.googleusercontent.com',
    iosClientId: '165461244282-6iu1m9dp6hg5efsm5662sht2gn6i5ngv.apps.googleusercontent.com',
    iosBundleId: 'com.example.salaryTrackingApp',
  );
}
